### ISSUE TITLE
Version 0.93 import failure

### ISSUE THREAD

**Issue by lelit** [dw/py-lmdb#165]
Investigating a problem within one of my CI test suites, that started including just released 0.93 of lmdb, I get the following in a scratch Python 3.6 virtualenv:
```
$ python3.6 -m venv e
$ source e/bin/activate
$ pip install lmdb
Collecting lmdb
  Downloading lmdb-0.93-py3-none-any.whl
Collecting cffi>=0.8 (from lmdb)
  Using cached cffi-1.10.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=0.8->lmdb)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 471kB/s 
Installing collected packages: pycparser, cffi, lmdb
  Running setup.py install for pycparser ... done
Successfully installed cffi-1.10.0 lmdb-0.93 pycparser-2.18
$ python
Python 3.6.1+ (heads/3.6:af839fe2fe, Mar 22 2017, 08:21:52) 
[GCC 6.3.0 20170316] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lmdb
gcc: error: /FIPython.h: File o directory non esistente
Traceback (most recent call last):
  File "/tmp/e/lib/python3.6/site-packages/lmdb/__init__.py", line 42, in <module>
    from lmdb.cpython import *
ModuleNotFoundError: No module named 'lmdb.cpython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/local/python3.6/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/python3.6/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/python3.6/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/e/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/usr/local/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/python3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/python3.6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/python3.6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/python3.6/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/local/python3.6/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/python3.6/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/e/lib/python3.6/site-packages/lmdb/__init__.py", line 48, in <module>
    from lmdb.cffi import *
  File "/tmp/e/lib/python3.6/site-packages/lmdb/cffi.py", line 364, in <module>
    library_dirs=_config_vars['extra_library_dirs'])
  File "/tmp/e/lib/python3.6/site-packages/cffi/api.py", line 438, in verify
    lib = self.verifier.load_library()
  File "/tmp/e/lib/python3.6/site-packages/cffi/verifier.py", line 114, in load_library
    self._compile_module()
  File "/tmp/e/lib/python3.6/site-packages/cffi/verifier.py", line 211, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/tmp/e/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/tmp/e/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by dw** [comment]
Grumbe, same issue as in #136... Forgot to look at that before making another release. Fix is simple, will delete the bad egg when I get home

**Comment by lelit** [comment]
Hope so 😄, but to be clear, this is on GNU/Linux, and pip installed it from the wheel...

**Comment by lelit** [comment]
Oh, maybe you mean that wheel is wrong and it is not really for the GNU/Linux arch...

**Comment by dw** [comment]
I deleted that wheel.. has the problem abated?

**Comment by lelit** [comment]
Yes, it seems working as expected: now it downloaded the .tar.gz source archive.

Thank you!
