### ISSUE TITLE
Segfault with dupsort put

### ISSUE THREAD

**Issue by jnwatson** [dw/py-lmdb#173]
### Affected Operating Systems
* Linux

### Affected py-lmdb Version
0.93

### py-lmdb Installation Method
both sudo pip install lmdb and install from source

### Using bundled or distribution-provided LMDB library?
Bundled

### Distribution name and LMDB library version
Python 3.6.4, 0.9.18, cpython mode
### Machine "free -m" output
              total        used        free      shared  buff/cache   available
Mem:          32018        8388       12036        1471       11594       23745
Swap:         32619           0       32619
0

### Other important machine info
Tested on Ubuntu 17.10, 16.04

### Describe Your Problem
It seg faults in 
```#0  mdb_cursor_put (mc=<optimized out>, key=<optimized out>, data=<optimized out>, flags=<optimized out>) at lib/mdb.c:6596
#1  0x00007ffff661473b in mdb_put (txn=0x555555873e80, dbi=2, key=key@entry=0x7fffffffcd40, data=data@entry=0x7fffffffcd50, flags=flags@entry=0) at lib/mdb.c:8780
#2  0x00007ffff65ffd7a in trans_put (self=0x7ffff636ab90, args=<optimized out>, kwds=<optimized out>) at lmdb/cpython.c:3294
#3  0x00007ffff79793fa in _PyCFunction_FastCallDict (func_obj=0x7ffff5ed6948, args=0x5555557eb480, nargs=<optimized out>, kwargs=kwargs@entry=0x0) at Objects/methodobject.c:231
#4  0x00007ffff79795e3 in _PyCFunction_FastCallKeywords (func=func@entry=0x7ffff5ed6948, stack=<optimized out>, nargs=nargs@entry=2, kwnames=kwnames@entry=0x0)
    at Objects/me```

The line number might be a little off. It fails on the following line in mdb.c:
```mp->mp_ptrs[i] = fp->mp_ptrs[i] + offset;```

### More info
Workaround: 

After recompiling the c module for debug, the problem went away. I identified the specific gcc optimization that disabling causes the problem to go away.

In setup.py:
```# distutils perplexingly forces NDEBUG for package code!
extra_compile_args = ['-UNDEBUG', '-fvect-cost-model=cheap']```

The new part is the -fvect-cost-model=cheap. (gcc -O3 the default is -fvect-cost-model=dynamic). This makes sense because it is crashing on an SSE instruction.

It looks like this is a problem with upstream lmdb (or gcc?!). I'll put together a C test case and submit upstream.

In the meantime, it would be prudent to add the compiler argument and release. I'll submit a PR.

**Comment by jnwatson** [comment]
And here's the file:
```
import lmdb
import tempfile

def crash_me():
    tf = tempfile.TemporaryDirectory()
    env = lmdb.open(tf.name + '/another.lmdb', max_dbs=2)
    db = env.open_db(b'foo', dupsort=True)

    with env.begin(db=db, buffers=False, write=True) as txn:
        txn.put(b'a', b'\x00\x00\x00\x00\x00\x00\x00\x00')
        txn.put(b'a', b'\x05')
        txn.put(b'a', b'\t')
        txn.put(b'a', b'\r')
        txn.put(b'a', b'\x11')
        txn.put(b'a', b'\x15')
        txn.put(b'a', b'\x19')
        txn.put(b'a', b'\x1d')
        txn.put(b'a', b'!')
        txn.put(b'a', b'%')
        txn.put(b'a', b')')
        txn.put(b'a', b'-')
        txn.put(b'a', b'1')
        txn.put(b'a', b'5')
        print("Didn't crash")

crash_me()
```

**Comment by dw** [comment]
Guessing 98% it's a bug in upstream, you might want to chat with them, but
they always ask for a C reproduction. Maybe try your luck with the
reproduction above :)

**Comment by jnwatson** [comment]
I have duplicated the bug in C town and reported it to OpenLDAP bug tracker.

**Comment by jnwatson** [comment]
Bug is fixed in upstream. https://github.com/openldap/openldap/commit/3b0f68a462355c5d565abff20d1515dce2afe697

Do you typically wait for an upstream release?

**Comment by dw** [comment]
I've cherry-picked quite a lot in the past, when the commits were small enough and reasonably easy to understand. Just as long as 'git log' in the lib/ directory still makes it obvious what the base version is and what fixes are on top :)

**Comment by jnwatson** [comment]
The diff is 2 lines, so it is pretty easy to make out.
