### ISSUE TITLE
 Won't implicitly convert Unicode to bytes，use .encode()

### ISSUE THREAD

**Issue by Jasonsey** [dw/py-lmdb#181]
- env：python3
- os：ubuntu/win10
- code：
``` Python
    ...
        with self.env.begin(write=True) as txn:
            for k, v in cache.items():
                print(k, type(k), type(k.encode().decode('unicode_escape')))
                txn.put(k, v) 
    ...
```
- disc: 
    1. when i put cache = {'name': bytes} : 
    ``` Shell
    Traceback (most recent call last):
      File "run.py", line 4, in <module>
        train.run()
      File "/root/max/look_for_similar_pictures/siameseNet/train.py", line 42, in run
        dataset = Dataset()
      File "/root/max/look_for_similar_pictures/siameseNet/dataset.py", line 26, in __init__
        self.init_db()
      File "/root/max/look_for_similar_pictures/siameseNet/dataset.py", line 47, in init_db
        tool.create_dataset(self.db_path + 'positive', positive_data, index=1, checkValid=True)
      File "/root/max/look_for_similar_pictures/siameseNet/lmdb.py", line 85, in create_dataset
        self.write_cache(cache)
      File "/root/max/look_for_similar_pictures/siameseNet/lmdb.py", line 35, in write_cache
       txn.put(k, v)
    TypeError: Won't implicitly convert Unicode to bytes; use .encode()
    ``` 
    2. i try `txn.put(k.encode(), v)`, but i always happen...
    3. so what can i do to cover it?

**Comment by Jasonsey** [comment]
i think what happen，thank you all the same！

**Comment by 990248516** [comment]
> 我想发生了什么，谢谢你们！

I also encountered this problem, how did you solve it?

**Comment by moyans** [comment]
[https://stackoverflow.com/questions/43805999/python3-and-not-is-python2-typeerror-wont-implicitly-convert-unicode-to-byt](url)
txn.put(str(k).encode(), str(v).encode())
