### ISSUE TITLE
Installation on Windows requiring Visual C++ 9.0

### ISSUE THREAD

**Issue by kroggen** [dw/py-lmdb#183]
### Affected Operating Systems

* Windows

### Affected py-lmdb Version

    current

### py-lmdb Installation Method

    pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled

### Errors/exceptions Encountered

```
C:\temp>c:\Python27\Scripts\pip.exe install lmdb
Collecting lmdb
  Using cached https://files.pythonhosted.org/packages/cb/31/5be8f436b56733d9e69
c721c358502f4d77b627489a459978686be7db65f/lmdb-0.94.tar.gz
Installing collected packages: lmdb
  Running setup.py install for lmdb ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\bernardo\\appdata\\local\\temp\\pip-install-ezzh
oc\\lmdb\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().re
place('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --r
ecord c:\users\bernardo\appdata\local\temp\pip-record-lp_omw\install-record.txt
--single-version-externally-managed --compile:
    py-lmdb: Using bundled liblmdb; override with LMDB_FORCE_SYSTEM=1.
    py-lmdb: Using CPython extension; override with LMDB_FORCE_CFFI=1.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\lmdb
    copying lmdb\cffi.py -> build\lib.win-amd64-2.7\lmdb
    copying lmdb\tool.py -> build\lib.win-amd64-2.7\lmdb
    copying lmdb\_config.py -> build\lib.win-amd64-2.7\lmdb
    copying lmdb\__init__.py -> build\lib.win-amd64-2.7\lmdb
    copying lmdb\__main__.py -> build\lib.win-amd64-2.7\lmdb
    running build_ext
    building 'cpython' extension
    error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpyt
hon27

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\bernardo\\appdata\\local\\temp\\pip-install-ezzhoc\\lmdb\\setup.py';f=ge
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
ose();exec(compile(code, __file__, 'exec'))" install --record c:\users\bernardo\
appdata\local\temp\pip-record-lp_omw\install-record.txt --single-version-externa
lly-managed --compile" failed with error code 1 in c:\users\bernardo\appdata\loc
al\temp\pip-install-ezzhoc\lmdb\
```

### Describe What You Expected To Happen

I expected the installation to not require the compiler, as written on the documentation.

**Comment by dw** [comment]
It looks like the AppVeyor build has broken for some reason, and I have no bandwidth to look at this presently. If you visit pypi.org you should be able to find an older release with wheels. Simply pip install that specific version as a workaround

**Comment by dw** [comment]
Looks like "pip install lmdb==0.93" will get you a working version:
https://pypi.org/project/lmdb/0.93/#files

**Comment by kroggen** [comment]
Yes, it worked.

Thank you for the prompt response!

**Comment by kroggen** [comment]
Well, it installed but it does not run:

```
C:\temp>python address-book.py
Traceback (most recent call last):
  File "address-book.py", line 2, in <module>
    import lmdb
  File "C:\Python27\lib\site-packages\lmdb\__init__.py", line 48, in <module>
    from lmdb.cffi import *
  File "C:\Python27\lib\site-packages\lmdb\cffi.py", line 364, in <module>
    library_dirs=_config_vars['extra_library_dirs'])
  File "C:\Python27\lib\site-packages\cffi\api.py", line 451, in verify
    lib = self.verifier.load_library()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 104, in load_library
    self._compile_module()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 201, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 147, in msvc9_query_vcvarsall
    return EnvironmentInfo(arch, ver).return_env()
  File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
    [self.VCIncludes,
  File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 877, in VCIncludes
    return [os.path.join(self.si.VCInstallDir, 'Include'),
  File "C:\Python27\lib\site-packages\setuptools\msvc.py", line 556, in VCInstallDir
    raise distutils.errors.DistutilsPlatformError(msg)
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

**Comment by kroggen** [comment]
OK, I unset the environment variables `LMDB_FORCE_SYSTEM` and `LMDB_FORCE_CFFI` and it worked.

Thank you!
