### ISSUE TITLE
tool.py throwing exceptions on Win32

### ISSUE THREAD

**Issue by davidkhess** [dw/py-lmdb#83]
Windows 7 64 bit, Python2.7 32 bit, py-lmdb 0.84 installed via pip. Using virtualenv.

```
(flask) C:\xxx>python -mlmdb copy -e database backup
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\xxx\flask\lib\site-packages\lmdb\__main__.py", line 24, in <module>
    lmdb.tool.main()
  File "C:\xxx\flask\lib\site-packages\lmdb\tool.py", line 598, in main
    signal.signal(signal.SIGWINCH, _on_sigwinch)
AttributeError: 'module' object has no attribute 'SIGWINCH'

(flask) C:\Users\databakery\Desktop\StreetCred>
```

If you comment out line 598:

`#signal.signal(signal.SIGWINCH, _on_sigwinch)`

then you get:

```
(flask) C:\xxx>python -mlmdb copy -e database backup
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\xxx\flask\lib\site-packages\lmdb\__main__.py", line 24, in <module>
    lmdb.tool.main()
  File "C:\xxx\flask\lib\site-packages\lmdb\tool.py", line 599, in main
    _on_sigwinch()
  File "C:\xxx\flask\lib\site-packages\lmdb\tool.py", line 579, in _on_sigwinch
    _TERM_WIDTH, _TERM_HEIGHT = _get_term_width()
TypeError: 'int' object is not iterable

(flask) C:\Users\databakery\Desktop\StreetCred>
```

I tried a hack of this on line 567:

`def _get_term_width(default=(80, 40)):`

and that allowed the backup command to run successfully.

**Comment by dw** [comment]
Hi David!

Can you try master? Sorry, I have no access to a Windows machine at present.

**Comment by davidkhess** [comment]
Works. No more exceptions.

Thanks!
